version: "3"
services:
    pcloud-utils:
        image: "http://192.168.104.211/pointcloud-fronted/pcloud-utils/"
        container_name: "pcloud-utils"
        environment:
            - TZ=Asia/Shanghai
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        privileged: true
        ports:
            - "9999:80"
        restart: always
        logging:
            driver: "json-file"
            options:
                max-size: "20m"
                max-file: "3"
